server:
  port: 8083
  
spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
      - id: EMPLOYEE-SERVICE
        uri:
          lb://EMPLOYEE-SERVICE
        predicates:
        - Path=/employee/**
