spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservicedatabase
    username: root
    password: 123456
  mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL55Dialect
    
  application:
    name: PROJECT-SERVICE
eureka:
  instance:
    hostname: localhost
server:
  port: 9004